# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- pelican

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    virtualenv ~/virtualenvs/pelican
    cd ~/virtualenvs/pelican
    . bin/activate
    pip install pelican
    pip install Markdown
    mkdir ./pelican-themes/blue-penguin
    git clone https://github.com/jody-frankowski/blue-penguin.git ./pelican-themes
    pelican-themes --install ./pelican-themes/blue-penguin --verbose
    pelican content -o output -s pelicanconf.py &&
    ghp-import output -r origin -b master &&
    git push origin master
  displayName: 'Run a multi-line script'
